apiVersion: v1
kind: Service
metadata:
  name: poc-devops-front-local-service
#  namespace: poc-devops
spec:
  ports:
    - name: http
      port: 80
  type: LoadBalancer
  selector:
    apps: poc-devops-front-local-service
